

class VicsScenario extends Simulation {

  val httpProtocol = http
    .baseURL("http://localhost:8080")
    .inferHtmlResources(BlackList(""".*\.js""", """.*\.css""", """.*\.gif""", """.*\.jpeg""", """.*\.jpg""", """.*\.ico""", """.*\.woff""", """.*\.(t|o)tf""", """.*\.png"""), WhiteList())

  val headers_9 = Map("Accept" -> "application/json", "Content-Type" -> "application/json")
  val headers_10 = Map("Accept" -> "application/pdf", "Content-Type" -> "application/json")

  val uri1 = "http://localhost:8080"

  val scn = scenario("CanvassApp2")
    .exec(http("request_0")
      .post("/api/canvass/user/login")
      .basicAuth("admin@admin.me", "=EcPecu42535.")
      .resources(http("request_1")
        .get(uri1 + "/api/canvass/user/login/test?role=USER")))
    .pause(1)
    .exec(http("request_4")
      .get("/api/canvass/user/login/test?role=USER")
      .resources(http("request_5")
        .get(uri1 + "/api/canvass/constituency")))
    .pause(4)
    .exec(http("request_6")
      .get("/api/canvass/ward/constituency/911a68a5-5689-418d-b63d-b21545345f03"))
    .pause(1)
    .exec(http("request_7")
      .get("/api/canvass/ward/constituency/911a68a5-5689-418d-b63d-b21545345f03"))
    .pause(2)
    .exec(http("request_8")
      .get("/api/canvass/ward/E05001218/street"))
    .pause(9)
    .exec(http("request_9")
      .post("/api/canvass/elector/ward/E05001218/street/pdf")
      .headers(headers_10)
      .body(RawFileBody("CanvassApp2_0009_request.txt")))
    .pause(2)
    .exec(http("request_10")
      .get("/api/canvass/user/login/test?role=USER")
      .resources(http("request_11")
        .get(uri1 + "/api/canvass/ward?summary=true")))
    .pause(6)
    .exec(http("request_12")
      .post("/api/canvass/elector/voted")
      .headers(headers_9)
      .body(RawFileBody("CanvassApp2_0012_request.txt")))
    .pause(1)
    .exec(http("request_13")
      .post("/api/canvass/elector/voted")
      .headers(headers_9)
      .body(RawFileBody("CanvassApp2_0013_request.txt")))
    .pause(1)
    .exec(http("request_14")
      .post("/api/canvass/elector/voted")
      .headers(headers_9)
      .body(RawFileBody("CanvassApp2_0014_request.txt")))
    .pause(1)
    .exec(http("request_15")
      .post("/api/canvass/elector/voted")
      .headers(headers_9)
      .body(RawFileBody("CanvassApp2_0015_request.txt")))
    .pause(3)
    .exec(http("request_16")
      .post("/api/canvass/elector/voted")
      .headers(headers_9)
      .body(RawFileBody("CanvassApp2_0016_request.txt")))
    .pause(3)
    .exec(http("request_17")
      .post("/api/canvass/elector/voted")
      .headers(headers_9)
      .body(RawFileBody("CanvassApp2_0017_request.txt")))
    .pause(3)
    .exec(http("request_18")
      .post("/api/canvass/elector/voted")
      .headers(headers_9)
      .body(RawFileBody("CanvassApp2_0018_request.txt")))
    .pause(2)
    .exec(http("request_19")
      .post("/api/canvass/elector/voted")
      .headers(headers_9)
      .body(RawFileBody("CanvassApp2_0019_request.txt")))
    .pause(4)
    .exec(http("request_20")
      .get("/api/canvass/user/login/test?role=USER")
      .resources(http("request_21")
        .get(uri1 + "/api/canvass/constituency")))
    .pause(1)
    .exec(http("request_22")
      .get("/api/canvass/user/login/test?role=USER")
      .resources(http("request_23")
        .get(uri1 + "/api/canvass/constituency")))
    .pause(3)
    .exec(http("request_24")
      .get("/api/canvass/ward/constituency/911a68a5-5689-418d-b63d-b21545345f03"))
    .pause(3)
    .exec(http("request_25")
      .get("/api/canvass/ward/E05001218/street"))
    .pause(3)
    .exec(http("request_28")
      .post("/api/canvass/gotv/ward/E05001218/street/pdf")
      .headers(headers_10)
      .body(RawFileBody("CanvassApp2_0028_request.txt")))
    .pause(2)
    .exec(http("request_29")
      .get("/api/canvass/user/login/test?role=USER")
      .resources(http("request_30")
        .get(uri1 + "/api/canvass/constituency"),
        http("request_31")
          .get(uri1 + "/api/canvass/user/login/test?role=USER"),
        http("request_32")
          .get(uri1 + "/api/canvass/ward?summary=true")))
    .pause(6)
    .exec(http("request_33")
      .post("/api/canvass/elector/voted")
      .headers(headers_9)
      .body(RawFileBody("CanvassApp2_0033_request.txt")))
    .pause(3)
    .exec(http("request_34")
      .post("/api/canvass/elector/voted")
      .headers(headers_9)
      .body(RawFileBody("CanvassApp2_0034_request.txt")))

  setUp(scn.inject(atOnceUsers(1), constantUsersPerSec(1) during (5 minutes) randomized).protocols(httpProtocol))
}
