
server:
  port: 18085
  context-path: /api/pdf

pdfserver:
   pafApiBaseUrl: https://PAF-935689129.eu-west-1.elb.amazonaws.com/v1/
   pafApiToken: 54b2f52b860f40a4b9cb9d89061720c3e6d1bc14
   pafApiTimeout: 60000

logging.level.: INFO
logging.level:
  com.infinityworks: DEBUG