
server:
  port: 18085
  context-path: /api/pdf

pdfserver:
   pafApiBaseUrl: https://PAF-935689129.eu-west-1.elb.amazonaws.com/v1/
   pafApiToken: 90f88caae35a5b863ae2450b55688a559b52a343
   pafApiTimeout: 60000

logging.level.: INFO
logging.level:
  com.infinityworks: DEBUG